name = "remix-cloudflare-workers"
type = "javascript"

account_id = ""
route = ""
workers_dev = true
zone_id = ""

compatibility_date = "2021-12-11"

kv_namespaces = [
  {binding = "KV", id = "3610772a2ab04928a4a2671944f52256"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format = "service-worker"

# https://miniflare.dev/kv.html#persistence
[miniflare]
kv_persist = true
